import { collection, addDoc, doc, setDoc, serverTimestamp } from 'firebase/firestore';
import { db } from '../../firebase/config';

// Initialize sample data for pharmacy POS system
export const initializeSampleData = async () => {
  try {
    console.log('Initializing sample pharmacy data...');

    // Sample Medicines - Real Sri Lankan Pharmacy Medicines
    const sampleMedicines = [
      // Common Pain Relief & Fever - Popular Sri Lankan brands
      {
        name: 'Panadol Advance',
        genericName: 'Paracetamol',
        manufacturer: 'GlaxoSmithKline',
        barcode: '8999999580001',
        activeIngredient: 'paracetamol',
        category: 'Analgesics',
        type: 'OTC',
        dosageForm: 'Tablet',
        strength: '500mg',
        stockQuantity: 500, // INCREASED STOCK
        minStockLevel: 50,
        maxStockLevel: 800,
        reorderPoint: 100,
        costPrice: 25.00,
        sellingPrice: 32.00,
        mrp: 35.00,
        discount: 0,
        batchNumber: 'PAN240901',
        manufacturingDate: new Date('2024-06-15'),
        expiryDate: new Date('2026-06-15'),
        storageConditions: 'Store below 30°C',
        sideEffects: ['Nausea', 'Stomach upset'],
        contraindications: ['Severe liver disease'],
        interactions: [],
        prescriptionRequired: false,
        dosageInstructions: '1-2 tablets every 4-6 hours. Max 8 tablets per day',
        status: 'active',
        taxRate: 0,
        rackLocation: 'A-1-1',
        vendor: 'Hemas Pharmaceuticals',
        createdAt: serverTimestamp(),
        updatedAt: serverTimestamp()
      },
      {
        name: 'Panadol Extra',
        genericName: 'Paracetamol + Caffeine',
        manufacturer: 'GlaxoSmithKline',
        barcode: '8999999580011',
        activeIngredient: 'paracetamol + caffeine',
        category: 'Analgesics',
        type: 'OTC',
        dosageForm: 'Tablet',
        strength: '500mg + 65mg',
        stockQuantity: 400, // INCREASED STOCK
        minStockLevel: 40,
        maxStockLevel: 600,
        reorderPoint: 80,
        costPrice: 35.00,
        sellingPrice: 45.00,
        mrp: 50.00,
        discount: 0,
        batchNumber: 'PEX240901',
        manufacturingDate: new Date('2024-06-15'),
        expiryDate: new Date('2026-06-15'),
        storageConditions: 'Store below 30°C',
        sideEffects: ['Restlessness', 'Nausea'],
        contraindications: ['Severe liver disease', 'Caffeine sensitivity'],
        interactions: [],
        prescriptionRequired: false,
        dosageInstructions: '1-2 tablets every 4-6 hours. Max 6 tablets per day',
        status: 'active',
        taxRate: 0,
        rackLocation: 'A-1-2',
        vendor: 'Hemas Pharmaceuticals',
        createdAt: serverTimestamp(),
        updatedAt: serverTimestamp()
      },
      {
        name: 'Piriton',
        genericName: 'Chlorpheniramine Maleate',
        manufacturer: 'GlaxoSmithKline',
        barcode: '8999999580012',
        activeIngredient: 'chlorpheniramine maleate',
        category: 'Antihistamines',
        type: 'OTC',
        dosageForm: 'Tablet',
        strength: '4mg',
        stockQuantity: 180,
        minStockLevel: 45,
        maxStockLevel: 280,
        reorderPoint: 70,
        costPrice: 15.00,
        sellingPrice: 22.00,
        mrp: 25.00,
        discount: 0,
        batchNumber: 'PIR240901',
        manufacturingDate: new Date('2024-05-20'),
        expiryDate: new Date('2026-05-20'),
        storageConditions: 'Store in cool, dry place',
        sideEffects: ['Drowsiness', 'Dry mouth'],
        contraindications: ['Newborns', 'Severe asthma'],
        interactions: [{ ingredient: 'alcohol', severity: 'moderate' }],
        prescriptionRequired: false,
        dosageInstructions: '1 tablet 3 times daily or as directed',
        status: 'active',
        taxRate: 0,
        rackLocation: 'A-2-1',
        vendor: 'Hemas Pharmaceuticals',
        createdAt: serverTimestamp(),
        updatedAt: serverTimestamp()
      },
      {
        name: 'Disprin Regular',
        genericName: 'Aspirin',
        manufacturer: 'Reckitt Benckiser',
        barcode: '8999999580002',
        activeIngredient: 'aspirin',
        category: 'Analgesics',
        type: 'OTC',
        dosageForm: 'Tablet',
        strength: '300mg',
        stockQuantity: 150,
        minStockLevel: 30,
        maxStockLevel: 200,
        reorderPoint: 50,
        costPrice: 18.00,
        sellingPrice: 24.00,
        mrp: 28.00,
        discount: 0,
        batchNumber: 'DIS240902',
        manufacturingDate: new Date('2024-07-01'),
        expiryDate: new Date('2026-07-01'),
        storageConditions: 'Store in cool, dry place',
        sideEffects: ['Stomach irritation', 'Bleeding risk'],
        contraindications: ['Peptic ulcer', 'Children under 16'],
        interactions: [{ ingredient: 'warfarin', severity: 'high' }],
        prescriptionRequired: false,
        dosageInstructions: '1-2 tablets every 4 hours. Max 8 tablets per day',
        status: 'active',
        taxRate: 0,
        rackLocation: 'A-1-3',
        vendor: 'Link Natural Products',
        createdAt: serverTimestamp(),
        updatedAt: serverTimestamp()
      },
      {
        name: 'Brufen',
        genericName: 'Ibuprofen',
        manufacturer: 'Abbott',
        barcode: '8999999580013',
        activeIngredient: 'ibuprofen',
        category: 'Analgesics',
        type: 'OTC',
        dosageForm: 'Tablet',
        strength: '400mg',
        stockQuantity: 120,
        minStockLevel: 30,
        maxStockLevel: 180,
        reorderPoint: 45,
        costPrice: 42.00,
        sellingPrice: 55.00,
        mrp: 62.00,
        discount: 0,
        batchNumber: 'BRU240901',
        manufacturingDate: new Date('2024-06-10'),
        expiryDate: new Date('2026-06-10'),
        storageConditions: 'Store below 25°C',
        sideEffects: ['Stomach upset', 'Headache'],
        contraindications: ['Peptic ulcer', 'Severe heart disease'],
        interactions: [{ ingredient: 'warfarin', severity: 'high' }],
        prescriptionRequired: false,
        dosageInstructions: '1 tablet 3 times daily with food',
        status: 'active',
        taxRate: 0,
        rackLocation: 'A-1-4',
        vendor: 'Abbott Healthcare',
        createdAt: serverTimestamp(),
        updatedAt: serverTimestamp()
      },

      // Antibiotics - Common Sri Lankan prescriptions
      {
        name: 'Amoxil',
        genericName: 'Amoxicillin',
        manufacturer: 'GlaxoSmithKline',
        barcode: '8999999580003',
        activeIngredient: 'amoxicillin',
        category: 'Antibiotics',
        type: 'Prescription',
        dosageForm: 'Capsule',
        strength: '250mg',
        stockQuantity: 80,
        minStockLevel: 20,
        maxStockLevel: 120,
        reorderPoint: 35,
        costPrice: 85.00,
        sellingPrice: 110.00,
        mrp: 125.00,
        discount: 0,
        batchNumber: 'AMX240903',
        manufacturingDate: new Date('2024-05-20'),
        expiryDate: new Date('2026-05-20'),
        storageConditions: 'Store below 25°C',
        sideEffects: ['Diarrhea', 'Nausea', 'Skin rash'],
        contraindications: ['Penicillin allergy'],
        interactions: [{ ingredient: 'warfarin', severity: 'moderate' }],
        prescriptionRequired: true,
        dosageInstructions: '1 capsule 3 times daily for 7 days',
        status: 'active',
        taxRate: 0,
        rackLocation: 'B-2-1',
        vendor: 'State Pharmaceuticals Corporation',
        createdAt: serverTimestamp(),
        updatedAt: serverTimestamp()
      },
      {
        name: 'Augmentin',
        genericName: 'Amoxicillin + Clavulanic Acid',
        manufacturer: 'GlaxoSmithKline',
        barcode: '8999999580004',
        activeIngredient: 'amoxicillin + clavulanic acid',
        category: 'Antibiotics',
        type: 'Prescription',
        dosageForm: 'Tablet',
        strength: '625mg',
        stockQuantity: 60,
        minStockLevel: 15,
        maxStockLevel: 90,
        reorderPoint: 25,
        costPrice: 145.00,
        sellingPrice: 185.00,
        mrp: 210.00,
        discount: 0,
        batchNumber: 'AUG240904',
        manufacturingDate: new Date('2024-04-10'),
        expiryDate: new Date('2026-04-10'),
        storageConditions: 'Store below 25°C',
        sideEffects: ['Diarrhea', 'Nausea', 'Vomiting'],
        contraindications: ['Penicillin allergy', 'Liver disease'],
        interactions: [{ ingredient: 'warfarin', severity: 'moderate' }],
        prescriptionRequired: true,
        dosageInstructions: '1 tablet twice daily with food for 5-7 days',
        status: 'active',
        taxRate: 0,
        rackLocation: 'B-2-2',
        vendor: 'State Pharmaceuticals Corporation',
        createdAt: serverTimestamp(),
        updatedAt: serverTimestamp()
      },
      {
        name: 'Erythromycin',
        genericName: 'Erythromycin',
        manufacturer: 'State Pharmaceuticals Corporation',
        barcode: '8999999580014',
        activeIngredient: 'erythromycin',
        category: 'Antibiotics',
        type: 'Prescription',
        dosageForm: 'Tablet',
        strength: '250mg',
        stockQuantity: 45,
        minStockLevel: 15,
        maxStockLevel: 75,
        reorderPoint: 25,
        costPrice: 125.00,
        sellingPrice: 165.00,
        mrp: 185.00,
        discount: 0,
        batchNumber: 'ERY240901',
        manufacturingDate: new Date('2024-05-15'),
        expiryDate: new Date('2026-05-15'),
        storageConditions: 'Store below 25°C',
        sideEffects: ['Nausea', 'Vomiting', 'Abdominal pain'],
        contraindications: ['Liver disease', 'Myasthenia gravis'],
        interactions: [{ ingredient: 'warfarin', severity: 'high' }],
        prescriptionRequired: true,
        dosageInstructions: '1 tablet 4 times daily before meals',
        status: 'active',
        taxRate: 0,
        rackLocation: 'B-2-3',
        vendor: 'State Pharmaceuticals Corporation',
        createdAt: serverTimestamp(),
        updatedAt: serverTimestamp()
      },
      {
        name: 'Ciprofloxacin',
        genericName: 'Ciprofloxacin',
        manufacturer: 'Cipla',
        barcode: '8999999580015',
        activeIngredient: 'ciprofloxacin',
        category: 'Antibiotics',
        type: 'Prescription',
        dosageForm: 'Tablet',
        strength: '500mg',
        stockQuantity: 35,
        minStockLevel: 10,
        maxStockLevel: 60,
        reorderPoint: 20,
        costPrice: 185.00,
        sellingPrice: 235.00,
        mrp: 265.00,
        discount: 0,
        batchNumber: 'CIP240901',
        manufacturingDate: new Date('2024-06-01'),
        expiryDate: new Date('2026-06-01'),
        storageConditions: 'Store below 25°C',
        sideEffects: ['Nausea', 'Diarrhea', 'Dizziness'],
        contraindications: ['Children under 18', 'Pregnancy'],
        interactions: [{ ingredient: 'antacids', severity: 'moderate' }],
        prescriptionRequired: true,
        dosageInstructions: '1 tablet twice daily for 7-10 days',
        status: 'active',
        taxRate: 0,
        rackLocation: 'B-2-4',
        vendor: 'Cipla Pharmaceuticals',
        createdAt: serverTimestamp(),
        updatedAt: serverTimestamp()
      },

      // Cough & Cold - Popular Sri Lankan remedies
      {
        name: 'Benadryl',
        genericName: 'Diphenhydramine + Ammonium Chloride',
        manufacturer: 'Johnson & Johnson',
        barcode: '8999999580016',
        activeIngredient: 'diphenhydramine + ammonium chloride',
        category: 'Cough & Cold',
        type: 'OTC',
        dosageForm: 'Syrup',
        strength: '100ml',
        stockQuantity: 95,
        minStockLevel: 25,
        maxStockLevel: 150,
        reorderPoint: 40,
        costPrice: 165.00,
        sellingPrice: 210.00,
        mrp: 235.00,
        discount: 0,
        batchNumber: 'BEN240901',
        manufacturingDate: new Date('2024-07-01'),
        expiryDate: new Date('2026-07-01'),
        storageConditions: 'Store below 30°C',
        sideEffects: ['Drowsiness', 'Dry mouth'],
        contraindications: ['Children under 2 years'],
        interactions: [{ ingredient: 'alcohol', severity: 'moderate' }],
        prescriptionRequired: false,
        dosageInstructions: '2 teaspoons 3 times daily',
        status: 'active',
        taxRate: 0,
        rackLocation: 'C-1-1',
        vendor: 'Johnson & Johnson',
        createdAt: serverTimestamp(),
        updatedAt: serverTimestamp()
      },
      {
        name: 'Procodin',
        genericName: 'Dextromethorphan + Chlorpheniramine',
        manufacturer: 'Glaxo Wellcome',
        barcode: '8999999580017',
        activeIngredient: 'dextromethorphan + chlorpheniramine',
        category: 'Cough & Cold',
        type: 'OTC',
        dosageForm: 'Syrup',
        strength: '100ml',
        stockQuantity: 85,
        minStockLevel: 20,
        maxStockLevel: 130,
        reorderPoint: 35,
        costPrice: 145.00,
        sellingPrice: 185.00,
        mrp: 210.00,
        discount: 0,
        batchNumber: 'PRO240901',
        manufacturingDate: new Date('2024-06-20'),
        expiryDate: new Date('2026-06-20'),
        storageConditions: 'Store below 30°C',
        sideEffects: ['Drowsiness', 'Nausea'],
        contraindications: ['Children under 6 years'],
        interactions: [{ ingredient: 'alcohol', severity: 'moderate' }],
        prescriptionRequired: false,
        dosageInstructions: '1-2 teaspoons 3-4 times daily',
        status: 'active',
        taxRate: 0,
        rackLocation: 'C-1-2',
        vendor: 'GlaxoSmithKline',
        createdAt: serverTimestamp(),
        updatedAt: serverTimestamp()
      },
      {
        name: 'Corex',
        genericName: 'Dextromethorphan + Chlorpheniramine + Phenylephrine',
        manufacturer: 'Pfizer',
        barcode: '8999999580018',
        activeIngredient: 'dextromethorphan + chlorpheniramine + phenylephrine',
        category: 'Cough & Cold',
        type: 'OTC',
        dosageForm: 'Syrup',
        strength: '100ml',
        stockQuantity: 70,
        minStockLevel: 18,
        maxStockLevel: 110,
        reorderPoint: 30,
        costPrice: 125.00,
        sellingPrice: 165.00,
        mrp: 185.00,
        discount: 0,
        batchNumber: 'COR240901',
        manufacturingDate: new Date('2024-05-25'),
        expiryDate: new Date('2026-05-25'),
        storageConditions: 'Store below 30°C',
        sideEffects: ['Drowsiness', 'Restlessness'],
        contraindications: ['Children under 4 years', 'High blood pressure'],
        interactions: [{ ingredient: 'MAO inhibitors', severity: 'high' }],
        prescriptionRequired: false,
        dosageInstructions: '1 teaspoon 3 times daily',
        status: 'active',
        taxRate: 0,
        rackLocation: 'C-1-3',
        vendor: 'Pfizer',
        createdAt: serverTimestamp(),
        updatedAt: serverTimestamp()
      },

      // Vitamins & Supplements
      {
        name: 'Vitamin C 1000mg',
        genericName: 'Ascorbic Acid',
        manufacturer: 'Nature\'s Bounty',
        barcode: '8999999580019',
        activeIngredient: 'ascorbic acid',
        category: 'Vitamins',
        type: 'OTC',
        dosageForm: 'Tablet',
        strength: '1000mg',
        stockQuantity: 200,
        minStockLevel: 50,
        maxStockLevel: 300,
        reorderPoint: 75,
        costPrice: 85.00,
        sellingPrice: 115.00,
        mrp: 135.00,
        discount: 0,
        batchNumber: 'VTC240901',
        manufacturingDate: new Date('2024-06-01'),
        expiryDate: new Date('2026-06-01'),
        storageConditions: 'Store in cool, dry place',
        sideEffects: ['Stomach upset (high doses)'],
        contraindications: ['Kidney stones history'],
        interactions: [],
        prescriptionRequired: false,
        dosageInstructions: '1 tablet daily with meals',
        status: 'active',
        taxRate: 0,
        rackLocation: 'D-1-1',
        vendor: 'Nature\'s Bounty',
        createdAt: serverTimestamp(),
        updatedAt: serverTimestamp()
      },
      {
        name: 'Vitamin D3 2000IU',
        genericName: 'Cholecalciferol',
        manufacturer: 'Carlson Labs',
        barcode: '8999999580020',
        activeIngredient: 'cholecalciferol',
        category: 'Vitamins',
        type: 'OTC',
        dosageForm: 'Capsule',
        strength: '2000IU',
        stockQuantity: 150,
        minStockLevel: 40,
        maxStockLevel: 220,
        reorderPoint: 60,
        costPrice: 125.00,
        sellingPrice: 165.00,
        mrp: 185.00,
        discount: 0,
        batchNumber: 'VTD240901',
        manufacturingDate: new Date('2024-05-15'),
        expiryDate: new Date('2026-05-15'),
        storageConditions: 'Store below 25°C',
        sideEffects: ['Nausea (high doses)'],
        contraindications: ['Hypercalcemia'],
        interactions: [{ ingredient: 'thiazide diuretics', severity: 'moderate' }],
        prescriptionRequired: false,
        dosageInstructions: '1 capsule daily with food',
        status: 'active',
        taxRate: 0,
        rackLocation: 'D-1-2',
        vendor: 'Carlson Labs',
        createdAt: serverTimestamp(),
        updatedAt: serverTimestamp()
      },
      {
        name: 'Multivitamin Complex',
        genericName: 'Multivitamin & Minerals',
        manufacturer: 'Centrum',
        barcode: '8999999580021',
        activeIngredient: 'multivitamin & minerals',
        category: 'Vitamins',
        type: 'OTC',
        dosageForm: 'Tablet',
        strength: 'Daily Formula',
        stockQuantity: 180,
        minStockLevel: 45,
        maxStockLevel: 270,
        reorderPoint: 70,
        costPrice: 165.00,
        sellingPrice: 215.00,
        mrp: 245.00,
        discount: 0,
        batchNumber: 'MUL240901',
        manufacturingDate: new Date('2024-06-10'),
        expiryDate: new Date('2026-06-10'),
        storageConditions: 'Store in cool, dry place',
        sideEffects: ['Stomach upset if taken on empty stomach'],
        contraindications: ['Iron overload disorders'],
        interactions: [{ ingredient: 'tetracycline', severity: 'moderate' }],
        prescriptionRequired: false,
        dosageInstructions: '1 tablet daily with breakfast',
        status: 'active',
        taxRate: 0,
        rackLocation: 'D-1-3',
        vendor: 'Centrum',
        createdAt: serverTimestamp(),
        updatedAt: serverTimestamp()
      },

      // Antacids & Digestive
      {
        name: 'ENO',
        genericName: 'Sodium Bicarbonate + Citric Acid',
        manufacturer: 'GlaxoSmithKline',
        barcode: '8999999580022',
        activeIngredient: 'sodium bicarbonate + citric acid',
        category: 'Antacids',
        type: 'OTC',
        dosageForm: 'Powder',
        strength: '5g sachet',
        stockQuantity: 250,
        minStockLevel: 60,
        maxStockLevel: 400,
        reorderPoint: 90,
        costPrice: 12.00,
        sellingPrice: 18.00,
        mrp: 22.00,
        discount: 0,
        batchNumber: 'ENO240901',
        manufacturingDate: new Date('2024-07-01'),
        expiryDate: new Date('2026-07-01'),
        storageConditions: 'Store in dry place',
        sideEffects: ['Temporary bloating'],
        contraindications: ['Severe kidney disease', 'Heart failure'],
        interactions: [{ ingredient: 'aspirin', severity: 'low' }],
        prescriptionRequired: false,
        dosageInstructions: '1 sachet in water when needed. Max 2 per day',
        status: 'active',
        taxRate: 0,
        rackLocation: 'E-1-1',
        vendor: 'GlaxoSmithKline',
        createdAt: serverTimestamp(),
        updatedAt: serverTimestamp()
      },
      {
        name: 'Gaviscon',
        genericName: 'Aluminum Hydroxide + Magnesium Carbonate',
        manufacturer: 'Reckitt Benckiser',
        barcode: '8999999580023',
        activeIngredient: 'aluminum hydroxide + magnesium carbonate',
        category: 'Antacids',
        type: 'OTC',
        dosageForm: 'Liquid',
        strength: '200ml',
        stockQuantity: 120,
        minStockLevel: 30,
        maxStockLevel: 180,
        reorderPoint: 45,
        costPrice: 285.00,
        sellingPrice: 365.00,
        mrp: 395.00,
        discount: 0,
        batchNumber: 'GAV240901',
        manufacturingDate: new Date('2024-06-15'),
        expiryDate: new Date('2026-06-15'),
        storageConditions: 'Store below 30°C',
        sideEffects: ['Constipation', 'Diarrhea'],
        contraindications: ['Kidney disease'],
        interactions: [{ ingredient: 'tetracycline', severity: 'moderate' }],
        prescriptionRequired: false,
        dosageInstructions: '2-4 teaspoons after meals and at bedtime',
        status: 'active',
        taxRate: 0,
        rackLocation: 'E-1-2',
        vendor: 'Reckitt Benckiser',
        createdAt: serverTimestamp(),
        updatedAt: serverTimestamp()
      },

      // Blood Pressure & Heart
      {
        name: 'Amlodipine',
        genericName: 'Amlodipine Besylate',
        manufacturer: 'Pfizer',
        barcode: '8999999580024',
        activeIngredient: 'amlodipine besylate',
        category: 'Cardiovascular',
        type: 'Prescription',
        dosageForm: 'Tablet',
        strength: '5mg',
        stockQuantity: 90,
        minStockLevel: 25,
        maxStockLevel: 140,
        reorderPoint: 40,
        costPrice: 85.00,
        sellingPrice: 115.00,
        mrp: 135.00,
        discount: 0,
        batchNumber: 'AML240901',
        manufacturingDate: new Date('2024-05-10'),
        expiryDate: new Date('2026-05-10'),
        storageConditions: 'Store below 25°C',
        sideEffects: ['Ankle swelling', 'Dizziness', 'Flushing'],
        contraindications: ['Severe aortic stenosis'],
        interactions: [{ ingredient: 'grapefruit juice', severity: 'moderate' }],
        prescriptionRequired: true,
        dosageInstructions: '1 tablet once daily',
        status: 'active',
        taxRate: 0,
        rackLocation: 'F-1-1',
        vendor: 'Pfizer',
        createdAt: serverTimestamp(),
        updatedAt: serverTimestamp()
      },
      {
        name: 'Atenolol',
        genericName: 'Atenolol',
        manufacturer: 'AstraZeneca',
        barcode: '8999999580025',
        activeIngredient: 'atenolol',
        category: 'Cardiovascular',
        type: 'Prescription',
        dosageForm: 'Tablet',
        strength: '50mg',
        stockQuantity: 75,
        minStockLevel: 20,
        maxStockLevel: 115,
        reorderPoint: 35,
        costPrice: 45.00,
        sellingPrice: 65.00,
        mrp: 75.00,
        discount: 0,
        batchNumber: 'ATE240901',
        manufacturingDate: new Date('2024-04-20'),
        expiryDate: new Date('2026-04-20'),
        storageConditions: 'Store below 25°C',
        sideEffects: ['Fatigue', 'Cold hands/feet', 'Dizziness'],
        contraindications: ['Severe asthma', 'Heart block'],
        interactions: [{ ingredient: 'verapamil', severity: 'high' }],
        prescriptionRequired: true,
        dosageInstructions: '1 tablet once or twice daily',
        status: 'active',
        taxRate: 0,
        rackLocation: 'F-1-2',
        vendor: 'AstraZeneca',
        createdAt: serverTimestamp(),
        updatedAt: serverTimestamp()
      },

      // Diabetes
      {
        name: 'Metformin',
        genericName: 'Metformin Hydrochloride',
        manufacturer: 'Bristol-Myers Squibb',
        barcode: '8999999580026',
        activeIngredient: 'metformin hydrochloride',
        category: 'Antidiabetic',
        type: 'Prescription',
        dosageForm: 'Tablet',
        strength: '500mg',
        stockQuantity: 100,
        minStockLevel: 25,
        maxStockLevel: 150,
        reorderPoint: 40,
        costPrice: 25.00,
        sellingPrice: 35.00,
        mrp: 42.00,
        discount: 0,
        batchNumber: 'MET240901',
        manufacturingDate: new Date('2024-06-05'),
        expiryDate: new Date('2026-06-05'),
        storageConditions: 'Store below 25°C',
        sideEffects: ['Nausea', 'Diarrhea', 'Stomach upset'],
        contraindications: ['Kidney disease', 'Liver disease'],
        interactions: [{ ingredient: 'alcohol', severity: 'moderate' }],
        prescriptionRequired: true,
        dosageInstructions: '1 tablet twice daily with meals',
        status: 'active',
        taxRate: 0,
        rackLocation: 'G-1-1',
        vendor: 'Bristol-Myers Squibb',
        createdAt: serverTimestamp(),
        updatedAt: serverTimestamp()
      },
      {
        name: 'Glibenclamide',
        genericName: 'Glibenclamide',
        manufacturer: 'Sanofi',
        barcode: '8999999580027',
        activeIngredient: 'glibenclamide',
        category: 'Antidiabetic',
        type: 'Prescription',
        dosageForm: 'Tablet',
        strength: '5mg',
        stockQuantity: 85,
        minStockLevel: 20,
        maxStockLevel: 130,
        reorderPoint: 35,
        costPrice: 35.00,
        sellingPrice: 48.00,
        mrp: 55.00,
        discount: 0,
        batchNumber: 'GLI240901',
        manufacturingDate: new Date('2024-05-25'),
        expiryDate: new Date('2026-05-25'),
        storageConditions: 'Store below 25°C',
        sideEffects: ['Hypoglycemia', 'Weight gain'],
        contraindications: ['Type 1 diabetes', 'Severe kidney disease'],
        interactions: [{ ingredient: 'alcohol', severity: 'high' }],
        prescriptionRequired: true,
        dosageInstructions: '1 tablet once daily before breakfast',
        status: 'active',
        taxRate: 0,
        rackLocation: 'G-1-2',
        vendor: 'Sanofi',
        createdAt: serverTimestamp(),
        updatedAt: serverTimestamp()
      },

      // Popular Sri Lankan Traditional Medicines
      {
        name: 'Samahan',
        genericName: 'Ayurvedic Herbal Mix',
        manufacturer: 'Link Natural Products',
        barcode: '8999999580028',
        activeIngredient: 'coriander, ginger, pepper, etc',
        category: 'Herbal',
        type: 'OTC',
        dosageForm: 'Powder',
        strength: '4g sachet',
        stockQuantity: 300,
        minStockLevel: 75,
        maxStockLevel: 500,
        reorderPoint: 120,
        costPrice: 15.00,
        sellingPrice: 22.00,
        mrp: 25.00,
        discount: 0,
        batchNumber: 'SAM240901',
        manufacturingDate: new Date('2024-07-01'),
        expiryDate: new Date('2026-07-01'),
        storageConditions: 'Store in cool, dry place',
        sideEffects: ['Mild stomach warming'],
        contraindications: ['Severe stomach ulcer'],
        interactions: [],
        prescriptionRequired: false,
        dosageInstructions: '1 sachet in hot water 2-3 times daily',
        status: 'active',
        taxRate: 0,
        rackLocation: 'H-1-1',
        vendor: 'Link Natural Products',
        createdAt: serverTimestamp(),
        updatedAt: serverTimestamp()
      },
      {
        name: 'Siddhalepa Balm',
        genericName: 'Ayurvedic Pain Relief Balm',
        manufacturer: 'Hettigoda Industries',
        barcode: '8999999580029',
        activeIngredient: 'wintergreen oil, eucalyptus oil, menthol',
        category: 'Topical',
        type: 'OTC',
        dosageForm: 'Balm',
        strength: '20g',
        stockQuantity: 200,
        minStockLevel: 50,
        maxStockLevel: 350,
        reorderPoint: 80,
        costPrice: 85.00,
        sellingPrice: 115.00,
        mrp: 135.00,
        discount: 0,
        batchNumber: 'SID240901',
        manufacturingDate: new Date('2024-06-20'),
        expiryDate: new Date('2026-06-20'),
        storageConditions: 'Store below 30°C',
        sideEffects: ['Skin irritation (sensitive skin)'],
        contraindications: ['Open wounds', 'Children under 2'],
        interactions: [],
        prescriptionRequired: false,
        dosageInstructions: 'Apply thin layer to affected area 2-3 times daily',
        status: 'active',
        taxRate: 0,
        rackLocation: 'H-1-2',
        vendor: 'Hettigoda Industries',
        createdAt: serverTimestamp(),
        updatedAt: serverTimestamp()
      },

      // More common medicines
      {
        name: 'Omeprazole',
        genericName: 'Omeprazole',
        manufacturer: 'AstraZeneca',
        barcode: '8999999580030',
        activeIngredient: 'omeprazole',
        category: 'Gastric',
        type: 'Prescription',
        dosageForm: 'Capsule',
        strength: '20mg',
        stockQuantity: 95,
        minStockLevel: 25,
        maxStockLevel: 145,
        reorderPoint: 40,
        costPrice: 125.00,
        sellingPrice: 165.00,
        mrp: 185.00,
        discount: 0,
        batchNumber: 'OME240901',
        manufacturingDate: new Date('2024-05-30'),
        expiryDate: new Date('2026-05-30'),
        storageConditions: 'Store below 25°C',
        sideEffects: ['Headache', 'Nausea', 'Diarrhea'],
        contraindications: ['Hypersensitivity to omeprazole'],
        interactions: [{ ingredient: 'clopidogrel', severity: 'moderate' }],
        prescriptionRequired: true,
        dosageInstructions: '1 capsule daily before breakfast',
        status: 'active',
        taxRate: 0,
        rackLocation: 'I-1-1',
        vendor: 'AstraZeneca',
        createdAt: serverTimestamp(),
        updatedAt: serverTimestamp()
      }
    ];

    // Add medicines to Firestore
    console.log('Adding medicines to Firestore...');
    for (const medicine of sampleMedicines) {
      await addDoc(collection(db, 'medicines'), medicine);
    }
    console.log(`Added ${sampleMedicines.length} medicines`);

    // Sample Patients - Sri Lankan example data
    const samplePatients = [
      {
        name: 'Kumara Perera',
        nic: '200123456789',
        contact: '0771234567',
        phoneNumber: '0771234567',
        age: '23',
        address: 'No. 45, Galle Road, Colombo 03',
        gender: 'Male',
        bloodGroup: 'O+',
        medicalNotes: 'No known allergies',
        dateOfBirth: '2001-05-15',
        totalPurchases: 0,
        createdAt: serverTimestamp(),
        updatedAt: serverTimestamp(),
        lastVisit: serverTimestamp()
      },
      {
        name: 'Sunethra Silva',
        nic: '198567890123',
        contact: '0712345678',
        phoneNumber: '0712345678',
        age: '39',
        address: 'No. 78, Kandy Road, Kegalle',
        gender: 'Female',
        bloodGroup: 'A+',
        medicalNotes: 'Allergic to penicillin',
        dateOfBirth: '1985-12-08',
        totalPurchases: 0,
        createdAt: serverTimestamp(),
        updatedAt: serverTimestamp(),
        lastVisit: serverTimestamp()
      },
      {
        name: 'Ranil Fernando',
        nic: '197234567890',
        contact: '0763456789',
        phoneNumber: '0763456789',
        age: '52',
        address: 'No. 123, Main Street, Matara',
        gender: 'Male',
        bloodGroup: 'B+',
        medicalNotes: 'Diabetic patient',
        dateOfBirth: '1972-08-22',
        totalPurchases: 0,
        createdAt: serverTimestamp(),
        updatedAt: serverTimestamp(),
        lastVisit: serverTimestamp()
      },
      {
        name: 'Nishani Jayawardena',
        nic: '199678901234',
        contact: '0754567890',
        phoneNumber: '0754567890',
        age: '28',
        address: 'No. 56, Temple Road, Nugegoda',
        gender: 'Female',
        bloodGroup: 'AB+',
        medicalNotes: 'Hypertension',
        dateOfBirth: '1996-03-10',
        totalPurchases: 0,
        createdAt: serverTimestamp(),
        updatedAt: serverTimestamp(),
        lastVisit: serverTimestamp()
      },
      {
        name: 'Chaminda Rathnayake',
        nic: '198856789012',
        contact: '0745678901',
        phoneNumber: '0745678901',
        age: '36',
        address: 'No. 89, Hill Street, Badulla',
        gender: 'Male',
        bloodGroup: 'O-',
        medicalNotes: 'No known conditions',
        dateOfBirth: '1988-11-05',
        totalPurchases: 0,
        createdAt: serverTimestamp(),
        updatedAt: serverTimestamp(),
        lastVisit: serverTimestamp()
      }
    ];

    // Add patients to Firestore
    console.log('Adding sample patients to Firestore...');
    for (const patient of samplePatients) {
      await addDoc(collection(db, 'patients'), patient);
    }
    console.log(`Added ${samplePatients.length} sample patients`);

    return { success: true, message: 'Sample data initialized successfully' };
  } catch (error) {
    console.error('Error initializing sample data:', error);
    return { success: false, message: error.message };
  }
};

// Function to clear all data (for testing purposes)
export const clearAllData = async () => {
  try {
    console.log('This function would clear all data. Implementation depends on Firebase Admin SDK.');
    // Note: Clearing collections requires Firebase Admin SDK or manual deletion
    // This is just a placeholder for the structure
    return { success: true, message: 'Data clearing completed' };
  } catch (error) {
    console.error('Error clearing data:', error);
    return { success: false, message: error.message };
  }
};
